apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: golang-20524
  janus-idp.io/tekton: golang-20524
  backstage.io/kubernetes-id: golang-20524
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: golang-20524
resources:
- deployment.yaml
- route.yaml
- service.yaml
